apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-pbso
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-pbso
    app.kubernetes.io/part-of: tkrw-pr712-0075-0042-app
  name: devfile-sample-pbso
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-pbso
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-pbso
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0042-tenant/tkrw-pr712-0075-0042-app/devfile-sample-pbso@sha256:40923a191ee92756d1020b80f67583c08af01887a10a63ed03f0888203407958
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
